### ISSUE TITLE
Error on Loading the command

### ISSUE THREAD

**Issue by Richard69s** [wildbook/R2Mods#20] opened 2020-08-16 22:07 UTC
The problem is that i reload the game over and over and over again but it still says it doesn't recognize it i am doing "mod_wb_set_multiplier 4" i have reinstalled it  2 times and updated my ROR2 to 1.0 but there is no config file i checked it may be this so maybe you can send a config file if that is the problem

**Comment by wildbook** [comment] 2020-08-19 15:01
I'm not sure what's causing that, but it's working just fine for me and others. My guess would be that you're missing a dependency. Update the mod again and make sure you also got all dependencies installed.

If it's still not working after that it'd be nice if you could post your RoR2 logs.

Closing for now as I don't think it's caused by Multitudes directly, feel free to re-open if it is.

**Closed as completed by wildbook** 2020-08-19 15:01 UTC
